### ISSUE TITLE
iOS Modal Background Scroll

### ISSUE THREAD

**Issue by diiq** [react-bootstrap/react-overlays#173] opened 2017-05-05 14:40 UTC
On iOS, the background scrolls when a modal is open and the user makes a pan gesture.

On desktop, scroll is prevented. 

This is true even of the sample modal: https://react-bootstrap.github.io/react-overlays/#modals .

Scroll should be prevented on all platforms.

(Forgive me if this is the same bug as #148 , but I struggled to understand precisely what that issue was about.)

I haven't come up with an acceptable workaround yet, but I will post here/open a PR if I do.

**Comment by victsant** [comment] 2017-07-28 16:18
I am having the same issue is there any update on this issue?

**Comment by Darrken** [comment] 2017-10-31 20:55
Actually on the desktop scroll isn't always prevented.  I'm not sure if this should be a separate issue or not but it's probably related.  In my app tabbing through the elements in the modal will eventually get you into the browser address bar, then when it goes back to the modal the background jumps to the top of the document.  When closing the modal, it does jump back to where it originally opened, at least.

You can see this effect in the react-overlays demo (but it's in reverse for some reason I haven't figured out, so tabbing backwards will jump to the bottom of the document).

Steps to reproduce:
1. Go to the [modal demo](https://react-bootstrap.github.io/react-overlays/#modals)
2. Click the "open modal" button
3. Shift-Tab once
4. The background doc jumps down to the Affix section.

I tried using an alternate [no-scroll](https://github.com/davidtheclark/no-scroll) and [focus-trap](https://github.com/davidtheclark/focus-trap) because they work very well on their own, but they don't play very well with this modal as they're trying to the same things (like calculating screen width minus scrollbar).

**Comment by mcmire** [comment] 2018-02-15 19:18
Sorry to uproot this issue but I've definitely noticed some weirdness on iOS with regard to modals. The background behind the modal doesn't scroll immediately if you try to swipe up, you kinda have to flick it, but I've definitely been able to reproduce it. I think it has to do with the rubber-band effect in iOS Safari. I forget what I searched for, but eventually I found [iNoBounce](https://www.npmjs.com/package/inobounce). Since you can toggle its behavior, I made it so that it was turned on when a modal is open and turned off when a modal was closed, and that seemed to help a lot.

(It's worth noting this has been an issue for Bootstrap in the past as well: https://github.com/twbs/bootstrap/issues/15852. Not sure if it still is or what -- but it's not a unique issue.)

**Comment by taion** [comment] 2018-02-15 20:35
Looks like it's a CSS issue and an upstream CANTFIX, then – so we'll close it out here as well.

**Closed by taion** 2018-02-15 20:35 UTC
