### ISSUE TITLE
calculatePosition() only clamps to one axis

### ISSUE THREAD

**Issue by viridia** [react-bootstrap/react-overlays#112] opened 2016-08-27 00:18 UTC
If you set placement to 'top' or 'bottom' it ensures that the component is horizontally within the container but not vertically; vice versa for 'left' and 'right' placement. I'd like for the component position to be within all four sides of the container regardless of placement. This does mean that the component might obscure part of the target if there's not enough room, but this is better than having the component be cut off (I'm using overlays for pop-up menus; having a menu get cut off is [a] bad, and [b] occurs with surprising frequency on the web.)

I'd be willing to code up a PR for this, but first I want to make sure that this behavior is acceptable.

**Comment by taion** [comment] 2016-08-27 01:56
Those are actually the intended behaviors so that React-Bootstrap matches Bootstrap's quirks there.

I think what you're looking for is `position="auto"`, which we don't currently support, but for which we do have an open issue to add support.

**Comment by viridia** [comment] 2016-08-27 03:25
Well, is there a spec for position=auto? I might be willing to implement it if there is. Assuming it meets my needs as well.

I'm using react-overlays as the basis for our own widget collection, so I'm not interested in bootstrap. But obviously I don't want to break anyone.

**Comment by taion** [comment] 2016-08-27 03:56
It'd be "whatever Bootstrap does", which should be pretty reasonable. I'm just not sure exactly what the formal spec is.

**Comment by viridia** [comment] 2016-08-27 04:20
Hmmm, well after a little research it appears that 'auto' isn't really the behavior that I want, so I'll have to figure out a different way to achieve it. Specifically, 'auto' flips the direction of the overlay placement if there isn't room on the preferred side, but it doesn't allow the overlay to cover the target - that may be the right thing for a tooltip, but it's not what I want for my popup menus.

I'm guess I'll try playing around with adjusting the styles in the onEnter handler, which is a bit of an inefficient hack (make the browser do the layout work twice).

**Comment by taion** [comment] 2016-11-15 19:15
We're not really planning on doing any further work here, so closing for now.

**Closed by taion** 2016-11-15 19:15 UTC
